modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Team-EnderIO/EnderIO/issues"
license="CC0"

[[mods]]
modId="enderio"
version="${mod_version}"
displayName="Ender IO"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, liliandev, Ferri_Arnus, dphaldes"
description="Compact conduits, painted things and all sorts of stuff and bling. This is the monolithic jar, containing all core modules."
displayURL="https://enderio.com/"
logoFile="logo.png"

[[dependencies.enderio]]
modId="minecraft"
type="required"
versionRange="${mcversion}"
side="BOTH"

[[dependencies.enderio]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
side="BOTH"

[[dependencies.enderio]]
modId="endercore"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[mods]]
modId="enderio_armory"
version="${mod_version}"
displayName="Ender IO Armory"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, liliandev, Ferri_Arnus, dphaldes"
description="The Ender IO Armory module."
displayURL="https://enderio.com/"
logoFile="logo.png"
featureFlags="META-INF/armory_feature_flags.json"

[[dependencies.enderio_armory]]
modId="minecraft"
type="required"
versionRange="${mcversion}"
side="BOTH"

[[dependencies.enderio_armory]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
side="BOTH"

[[dependencies.enderio_armory]]
modId="endercore"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[dependencies.enderio_armory]]
modId="enderio_base"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[mods]]
modId="enderio_base"
version="${mod_version}"
displayName="Ender IO Base"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, liliandev, Ferri_Arnus, dphaldes"
description="The base items and materials for the Ender IO Mods."
displayURL="https://enderio.com/"
logoFile="logo.png"

[[mixins]]
config="enderiobase.mixins.json"

[[dependencies.enderio_base]]
modId="minecraft"
type="required"
versionRange="${mcversion}"
side="BOTH"

[[dependencies.enderio_base]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
side="BOTH"

[[dependencies.enderio_base]]
modId="endercore"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[mods]]
modId="enderio_conduits"
version="${mod_version}"
displayName="Ender IO Conduits"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, liliandev, Ferri_Arnus, dphaldes"
description="The conduits module for Ender IO"
displayURL="https://enderio.com/"
logoFile="logo.png"

[[mixins]]
config="enderioconduits.mixins.json"

[[dependencies.enderio_conduits]]
modId="minecraft"
type="required"
versionRange="${mcversion}"
side="BOTH"

[[dependencies.enderio_conduits]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
side="BOTH"

[[dependencies.enderio_conduits]]
modId="endercore"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[dependencies.enderio_conduits]]
modId="enderio_base"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[mods]]
modId="enderio_conduits_modded"
version="${mod_version}"
displayName="Ender IO Modded Conduits"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, liliandev, Ferri_Arnus, dphaldes"
description="Adding AE2, RS2 and Mekanism conduits to Ender IO."
displayURL="https://enderio.com/"
logoFile="logo.png"

[[dependencies.enderio_conduits_modded]]
modId="minecraft"
type="required"
versionRange="${mcversion}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="endercore"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="enderio_base"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="enderio_conduits"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="mekanism"
type="optional"
versionRange="${mekanism_version_range}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="ae2"
type="optional"
versionRange="${ae2_version_range}"
side="BOTH"

[[dependencies.enderio_conduits_modded]]
modId="refinedstorage"
type="optional"
versionRange="${refinedstorage_version_range}"
side="BOTH"

[[mods]]
modId="enderio_machines"
version="${mod_version}"
displayName="Ender IO Machines"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, liliandev, Ferri_Arnus, dphaldes"
description="The machines module for Ender IO"
displayURL="https://enderio.com/"
logoFile="logo.png"
featureFlags="META-INF/machines_feature_flags.json"

[[mixins]]
config="enderio-machines.mixins.json"

[[dependencies.enderio_machines]]
modId="minecraft"
type="required"
versionRange="${mcversion}"
side="BOTH"

[[dependencies.enderio_machines]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
side="BOTH"

[[dependencies.enderio_machines]]
modId="endercore"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[dependencies.enderio_machines]]
modId="enderio_base"
type="required"
versionRange="${mod_version}"
side="BOTH"
